# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20161103_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='count',
            field=models.IntegerField(default=0, help_text='빌려준 회수'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='size',
            field=models.CharField(default='L', max_length=20, null=True),
        ),
    ]
